# Generated by Django 5.0.6 on 2024-12-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristdestination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
